version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - COHERE_API_KEY=ZexKVKGVm6Lg2ILnOofMumoV2mGT0o7prBL5l73X
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
